name: "Bug Report"
description: "Report a bug or problem with Pastetime"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Thank you for reporting a bug!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug in detail.
      placeholder: "A clear and concise description of the bug."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to '...'
        2. Enter '...'
        3. See error
      render: bash
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: "Describe what you expected."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: Add screenshots to help explain your problem.
      placeholder: "Drag and drop, or paste image here."
    validations:
      required: false

  - type: input
    id: device
    attributes:
      label: Device/Environment
      description: OS, browser, device (e.g. Windows, Chrome, iPhone)
      placeholder: "Windows 11, Chrome 115, Desktop"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Anything else we should know?
    validations:
      required: false
