name: "Feature Request"
description: "Suggest an idea or enhancement for Pastetime"
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Request

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Describe the problem or use case this feature would solve.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What would you like to see added or changed?
      placeholder: "A clear and concise description of what you want to happen."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Have you tried other solutions or workarounds?
      placeholder: "Any alternative solutions or features you’ve thought about?"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context, screenshots, or links
    validations:
      required: false
